# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d29eb6aa98f994764183bb329f738ba54c0579b270c6cf727423abc38a2872facba9a479a84ea48337ff57cd926a8ef1974fd8372b79759fa9913de5b8c5e43e

test:
  secret_key_base: 5a3bbf39d3049e3f4f66df1a8d60b98a4d9a46f3c365843fdb7ae4e8ceeeaa1e416bb8d0cb04fec3d45d36a453d1e58fd02888c45e229f13a57c56382c6d5913

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
